# Generated by Django 3.1.6 on 2021-02-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, unique=True)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Performers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('aliases', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('years_active', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=300, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=50, null=True)),
                ('boobs', models.CharField(blank=True, max_length=50, null=True)),
                ('tattoos', models.CharField(blank=True, max_length=50, null=True)),
                ('piercings', models.CharField(blank=True, max_length=50, null=True)),
                ('measurments', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.ratings')),
            ],
            options={
                'db_table': 'performers',
            },
        ),
    ]
