# Generated by Django 3.1.6 on 2021-02-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Performers',
            new_name='Performer',
        ),
    ]
