# Generated by Django 3.1.6 on 2021-02-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0002_auto_20210204_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
