# Generated by Django 3.1.6 on 2021-02-04 11:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0004_directors_genres_releasedates_studios_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(blank=True, max_length=150, null=True)),
                ('movie_cover', models.URLField(blank=True, null=True)),
                ('length', models.TimeField(blank=True, null=True)),
                ('movie_trailer', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gallary_urls', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.directors')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.ratings')),
                ('release_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.releasedates')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.studios')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('length', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gallary_urls', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.directors')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.movies')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.ratings')),
                ('release_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.releasedates')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.studios')),
            ],
            options={
                'db_table': 'scenes',
            },
        ),
    ]
