# Generated by Django 3.1.6 on 2021-02-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0006_auto_20210204_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='performers.Genres'),
        ),
        migrations.AddField(
            model_name='movie',
            name='performers',
            field=models.ManyToManyField(to='performers.Performer'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='performers.Tags'),
        ),
        migrations.AddField(
            model_name='scene',
            name='performers',
            field=models.ManyToManyField(to='performers.Performer'),
        ),
        migrations.AddField(
            model_name='scene',
            name='tags',
            field=models.ManyToManyField(to='performers.Tags'),
        ),
    ]
