# Generated by Django 3.1.6 on 2021-02-13 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0011_auto_20210206_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performers.ratings'),
        ),
        migrations.CreateModel(
            name='SceneCastTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.performer')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='performers.scene')),
            ],
            options={
                'db_table': 'scene_cast_table',
            },
        ),
        migrations.AlterField(
            model_name='scene',
            name='performers',
            field=models.ManyToManyField(related_name='performers', through='performers.SceneCastTable', to='performers.Performer'),
        ),
    ]
