# Generated by Django 3.1.6 on 2021-02-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0013_auto_20210215_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='movie_director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='movie_release_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='movierating',
        ),
        migrations.AlterField(
            model_name='performer',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performer_rating', to='performers.ratings'),
        ),
    ]
