# Generated by Django 3.1.6 on 2021-02-15 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0015_auto_20210215_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movierating',
            new_name='movie_rating',
        ),
        migrations.AlterField(
            model_name='performer',
            name='performer_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='performer_rating', to='performers.ratings'),
        ),
    ]
