# Generated by Django 3.1.6 on 2021-02-15 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performers', '0016_auto_20210215_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='performer_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie_director', to='performers.directors'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie_rating', to='performers.ratings'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie_release_date', to='performers.releasedates'),
        ),
    ]
